// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	return &ResourceBuilder{
		config: rac,
		res:    pcommon.NewResource(),
	}
}

// SetMysqlDbInstance sets provided value as "mysql.db.instance" attribute.
func (rb *ResourceBuilder) SetMysqlDbInstance(val string) {
	if rb.config.MysqlDbInstance.Enabled {
		rb.res.Attributes().PutStr("mysql.db.instance", val)
	}
}

// SetMysqlDbMysqlVersion sets provided value as "mysql.db.mysql_version" attribute.
func (rb *ResourceBuilder) SetMysqlDbMysqlVersion(val string) {
	if rb.config.MysqlDbMysqlVersion.Enabled {
		rb.res.Attributes().PutStr("mysql.db.mysql_version", val)
	}
}

// SetMysqlDbSystemVersion sets provided value as "mysql.db.system_version" attribute.
func (rb *ResourceBuilder) SetMysqlDbSystemVersion(val string) {
	if rb.config.MysqlDbSystemVersion.Enabled {
		rb.res.Attributes().PutStr("mysql.db.system_version", val)
	}
}

// SetMysqlInstanceEndpoint sets provided value as "mysql.instance.endpoint" attribute.
func (rb *ResourceBuilder) SetMysqlInstanceEndpoint(val string) {
	if rb.config.MysqlInstanceEndpoint.Enabled {
		rb.res.Attributes().PutStr("mysql.instance.endpoint", val)
	}
}

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	r := rb.res
	rb.res = pcommon.NewResource()
	return r
}
