// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("metricstoeventsconnector")
	ScopeName = "metricstoeventsconnector"
)

const (
	MetricsToLogsStability = component.StabilityLevelBeta
)
